site_name: VPdocs Training Program

nav:
  - Home: index.md
  - About: about.md

theme: 
  name: 'material'
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-5
        name: Switch to light mode


  