site_name: VPdocs Support Training Program
site_url: http://localhost:8000

nav:
  - Home: index.md
  - FortiClientEMS:
    - Overview: FortiClientEMS/index.md
    - FortiClient VPN: 
      - Initial Connection Issues: FortiClientEMS/VPN/init_conn.md
      - Addressing VPN Drops: FortiClientEMS/VPN/vpndrops.md
      - VPN Performance: FortiClientEMS/VPN/vpn_perf.md
      - Auto-Connect and Always-up: FortiClientEMS/VPN/auto_connect.md
      - DNS Issues: FortiClientEMS/VPN/dns.md
    - Zero Trust Network Access:
      - Overview: FortiClientEMS/ZTNA/index.md
      - ZTNA Certificate: FortiClientEMS/ZTNA/ztna_certificate.md
      - Posture Tags: FortiClientEMS/ZTNA/posture_tags.md
      - ZTNA connection issues: FortiClientEMS/ZTNA/ztna_server_conn.md
      - Fabric Connector issues: FortiClientEMS/ZTNA/fabric_connector.md
      - FortiGate WAD diagnostics analysis: FortiClientEMS/ZTNA/wad_diags.md
  - FortiSASE:
    - Overview: FortiSASE/index.md
    - Secure Private Access: FortiSASE/SPA/spa.md
    - IPsec VPN: FortiSASE/VPN/ipsec.md
  - FortiNextDLP:
    - Overview: FortiNextDLP/index.md
  - Practice: 
    - Labs: practice/labs.md
    - Quizzes: practice/quizzes.md
  - Demos:
    - FortiClientEMS: Demos/forticlient_demos.md
    - FortiSASE: Demos/fortisase_demos.md
  - About: about.md


plugins:
  # - social:
  #     enabled: true
  #     cache: true
  #     cache_dir: .cache/plugins/social
  #     cards: true
  #     log: true
  #     cards_dir: assets/images/social
  #     cards_layout_dir: layouts
  #     debug: true
  #     debug_on_build: false
  #     debug_grid: true
  #     debug_grid_step: 32
  #     debug_color: yellow
  - search

theme: 
  name: 'material'
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  logo: assets/Fortinet-logo-rgb-white-red.png
  features:
    - navigation.tabs # header tabs
    - navigation.sections # left sidebar navigation tabs
    - navigation.expand # expand sidebar sections
    - navigation.path # nav path on top
    - navigation.top 
    - toc.follow # sidebar nav follows w/ scrolling
    - toc.integrate # page nav part of sidebar
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.footnote.tooltips

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - footnotes




  