site_name: VPdocs Support Training Program
site_url: http://localhost:8000

nav:
  - Home: index.md
  - FortiClientEMS:
    - Overview: FortiClientEMS/index.md
    - FortiClient VPN: 
      - Initial Connection Issues: FortiClientEMS/VPN/init_conn.md
      - Addressing VPN Drops: FortiClientEMS/VPN/vpndrops.md
    - Zero Trust Network Access:
      - FortiClient-side Issues: FortiClientEMS/ZTNA/client-side-issues.md
  - FortiSASE:
    - Secure Private Access: FortiSASE/SPA/spa.md
    - IPsec VPN: FortiSASE/VPN/ipsec.md
  - Practice: 
    - Labs: practice/labs.md
    - Quizzes: practice/quizzes.md
  - About: about.md


plugins:
  - social:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/social
      cards: true
      log: true
      cards_dir: assets/images/social
      cards_layout_dir: layouts
      debug: true
      debug_on_build: false
      debug_grid: true
      debug_grid_step: 32
      debug_color: yellow
  - search

theme: 
  name: 'material'
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  logo: assets/Fortinet-logo-rgb-white-red.png
  features:
    - navigation.tabs # header tabs
    - navigation.sections # left sidebar navigation tabs
    - navigation.expand # expand sidebar sections
    - navigation.path # nav path on top
    - navigation.top 
    - toc.follow # sidebar nav follows w/ scrolling
    - toc.integrate # page nav part of sidebar
    - search.suggest
    - search.highlight
    - search.share




  