site_name: VPdocs Support Training Program
site_url: http://localhost:8000

nav:
  - Home: index.md
  - FortiClient:
    - Overview: FortiClient/index.md
    - New features:
      - Overview: FortiClient/New features/index.md
      - 7.4.1: FortiClient/New features/7.4.1.md
    - FortiClient VPN:
      - Overview: FortiClient/VPN/index.md
      - Initial Connection Issues: FortiClient/VPN/init_conn.md
      - Addressing VPN Drops: FortiClient/VPN/vpndrops.md
      - VPN Performance: FortiClient/VPN/vpn_perf.md
      - Auto-Connect and Always-up: FortiClient/VPN/auto_connect.md
      - DNS Issues: FortiClient/VPN/dns.md
    - Zero Trust Network Access:
      - Overview: FortiClient/ZTNA/index.md
      - ZTNA Certificate: FortiClient/ZTNA/ztna_certificate.md
      - Posture Tags: FortiClient/ZTNA/posture_tags.md
      - ZTNA connection issues: FortiClient/ZTNA/ztna_server_conn.md
      - Fabric Connector issues: FortiClient/ZTNA/fabric_connector.md
      - FortiGate WAD diagnostics analysis: FortiClient/ZTNA/wad_diags.md
  - EMS:
    - Overview: EMS/index.md
    - New features:
      - Overview: EMS/New features/index.md
      - 7.4.1: EMS/New features/7.4.1.md
    - EMS on Linux:
      - Navigating Linux: EMS/Linux/linux_basics.md
  - FortiSASE:
    - Overview: FortiSASE/index.md
    - Secure Private Access: FortiSASE/SPA/spa.md
    - IPsec VPN: FortiSASE/VPN/ipsec.md
  - FortiDLP:
    - Overview: FortiDLP/index.md
  - Practice: 
    - Labs: practice/labs.md
    - Quizzes: practice/quizzes.md
  - Demos:
    - FortiClient: Demos/forticlient_demos.md
    - FortiSASE: Demos/fortisase_demos.md
  - About: about.md


plugins:
  # - social:
  #     enabled: true
  #     cache: true
  #     cache_dir: .cache/plugins/social
  #     cards: true
  #     log: true
  #     cards_dir: assets/images/social
  #     cards_layout_dir: layouts
  #     debug: true
  #     debug_on_build: false
  #     debug_grid: true
  #     debug_grid_step: 32
  #     debug_color: yellow
  - search

theme: 
  name: 'material'
  custom_dir: overrides
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  logo: assets/Fortinet-logo-rgb-white-red.png
  features:
    - navigation.tabs # header tabs
    - navigation.sections # left sidebar navigation tabs
    - navigation.expand # expand sidebar sections
    - navigation.path # nav path on top
    - navigation.top
    - navigation.indexes
    - toc.follow # sidebar nav follows w/ scrolling
    - toc.integrate # page nav part of sidebar
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg




  